# Site wide configuration

title: Memesplicer Reboot
description: The personal blog of Butch Landingin
logo: logo_120x120.png# 120x120 px default image used for Twitter summary card
teaser: teaser_400x250.png # 400x250 px default teaser image used in image archive grid
page_lead_background: page_lead_background_1600x800.jpg
locale:
url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Butch Landingin
  email: butchland@gmail.com
  twitter: butchland
  google: 
    ad-client: 
    ad-slot: 
  bio: 
  avatar: biophoto_160x160.png # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
