# Site settings
title: Memesplicer Reborn
email: butchland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Butch Landingin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://butchland.github.io" # the base hostname & protocol for your site
twitter_username: butchland
github_username:  butchland

# Build settings
markdown: kramdown
gems:
   - jekyll-sitemap
