project:
  type: website

website:
  title: "Butch Landingin's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/butchland
      - icon: mastodon
        href: https://fosstodon.org/@butchland
  page-footer:
    background: light
    left: "Copyright 2023, Butch Landingin"
    right:
      - icon: github
        href: https://github.com/butchland
      - icon: mastodon
        href: https://fosstodon.org/@butchland

format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: auto


