project:
  type: website

website:
  title: "Butch Landingin's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/butchland
      - icon: twitter
        href: https://twitter.com/butchland
format:
  html:
    theme: cosmo
    css: styles.css



